AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template to set up a generic S3 static website bucket with redirect,
  CloudFront distribution, and Route53 alias record using an existing SSL certificate and DNS zone.

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket (e.g., subdomain.example.com).
  RedirectTarget:
    Type: String
    Description: The URL to which requests should be redirected (e.g., https://target.example.com).
  DomainName:
    Type: String
    Description: The domain name for the CloudFront distribution (e.g., subdomain.example.com).
  ACMCertificateARN:
    Type: String
    Description: The ARN of the ACM certificate for HTTPS (e.g., arn:aws:acm:us-east-1:123456789012:certificate/abc123).
  HostedZoneId:
    Type: String
    Description: The Route53 hosted zone ID for the domain (e.g., Z01XXXXXXXXXXXXXXXXXXX).

Resources:
  # S3 Bucket for Static Website Redirect
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RedirectTarget
          Protocol: https
      PublicAccessBlockConfiguration: # Disable Block Public Access for this bucket
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # S3 Bucket Policy to Allow Public Access
  RedirectBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RedirectBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: !Ref BucketName
            DomainName: !Sub "${BucketName}.s3-website-us-east-1.amazonaws.com"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: !Ref BucketName
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: ["GET", "HEAD"]
          CachedMethods: ["GET", "HEAD"]
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6" # AWS managed cache policy for minimal caching
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertificateARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases:
          - !Ref DomainName
        DefaultRootObject: ""

  # Route53 Alias Record
  Route53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: "UPDATEWITHYOURZONEIDHERE" # Hosted zone ID for CloudFront
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        EvaluateTargetHealth: false

Outputs:
  CloudFrontURL:
    Description: The CloudFront distribution domain name.
    Value: !GetAtt CloudFrontDistribution.DomainName
  Route53Alias:
    Description: The Route53 alias record for the domain.
    Value: !Ref DomainName
